### PR TITLE
Remove warnings_filter

### LINKED ISSUE #47: DeprecationWarning: warning_filter
I get this error when I try to build doc, macOS 13.4.1:

CleanShot 2023-08-03 at 1 12 43

### PR DESCRIPTION
**Pull request by timvink**
Closes https://github.com/rosscdh/mkdocs-markdownextradata-plugin/issues/47

### CODE REVIEW

**Review by reiterative — COMMENTED** [review]
+1 for this to clean up the DeprecationWarning that is currently output

**Comment by k3yss** [comment]
@rosscdh Ping! +1 for this

**Comment by rosscdh** [comment]
Thanks for the contrib! Sorry for the delay!

**Comment by philshem** [comment]
Hi @rosscdh, thanks for the merge. Any info about when this will show up in PyPi?

https://pypi.org/project/mkdocs-markdownextradata-plugin/#history

**Comment by rosscdh** [comment]
published 0.2.6

**Pull request merged**
